switch/switchblog/api/urls.py
from django.conf.urls import include, url
from api import views

urlpatterns = [
    url(r'^$', views.indexViews,name='index')
]

switch/switchblog/blog/urls.py
from django.conf.urls import include, url
from blog import views

urlpatterns = [
    url(r'^$', views.indexViews,name='blog-index'),
    url(r'^newsfeed/$', views.newsfeedViews,name='newsfeed'),
    url(r'^create-post/$', views.createPostView, name="create-post")
]

switch/switchblog/switchblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('useraccount.urls', namespace="useraccount")),
    url(r'^blog/',include('blog.urls', namespace="blog")),
    url(r'^api/',include('api.urls', namespace="api")),
]

switch/switchblog/useraccount/urls.py
from django.conf.urls import include, url
from useraccount import views

urlpatterns = [
    url(r'^$', views.indexView, name='index'),
    url(r'^sign_up$', views.signupView, name='sign_up'),
    url(r'^login$', views.loginView, name='login'),
    url(r'^logout$', views.logoutView, name='logout'),
    url(r'^forgot-password$', views.forgotPassswordView, name='forgot-password'),
    url(r'^reset-password$', views.resetPasswordView, name='reset-password'),
]

switch/switchblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<title>{% block title %}{% endblock title %}</title>
<!--

Template 2085 Neuron

http://www.tooplate.com/view/2085-neuron

-->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/font-awesome.min.css " %}">

<!-- Main css -->
<link rel="stylesheet" href="{% static "css/style.css " %}">
<link href="https://fonts.googleapis.com/css?family=Lora|Merriweather:300,400" rel="stylesheet">

</head>
<body>

<!-- PRE LOADER -->

<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>

<!-- Navigation section  -->

<div class="navbar navbar-default navbar-static-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>
               <a href="{% url 'blog:blog-index' %}" class="navbar-brand">SWITCH BLOG</a>
          </div>
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="{% url 'blog:blog-index' %}">Home</a></li>
                    <li><a href="{% url 'blog:newsfeed' %}">News Feed</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    {% if request.user.is_authenticated %}
                      <li><a href="{% url 'useraccount:logout' %}">Logout</a></li>
                    {% else %}
                      <li><a href="{% url 'useraccount:login' %}">Login</a></li>
                      <li><a href="{% url 'useraccount:sign_up' %}">Sign up</a></li>
                    {% endif %}
               </ul>
          </div>

  </div>
</div>

<!-- Home Section -->


<section id="home" class="main-home parallax-section">
     <div class="overlay"></div>
     <div id="particles-js"></div>
     <div class="container">
          <div class="row">

               <div class="col-md-12 col-sm-12">
                    <h1>Hello! This is Neuron.</h1>
                    <h4>Responsive Blog HTML CSS Website Template</h4>
                    <a href="#blog" class="smoothScroll btn btn-default">Discover More</a>
               </div>

          </div>
     </div>
</section>

<!-- Blog Section -->

<section id="blog">
    
     <div class="container">
        <div class="row">
            {% if messages %}
              {% for msg in messages %}
                <span> {{msg}}</span>
              {% endfor %}
            {% endif %}
        </div>
          <div class="row">
                {% block inner_content %}
               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="single-post.html">
                                   <img src="images/blog-image1.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">We Help You Create Perfect Modern Design</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> July 22, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 35 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a href="single-post.html" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="single-post.html">
                                   <img src="images/blog-image2.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">In pretium tellus et ante accumsan</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="images/author-image2.jpg" class="img-responsive img-circle"> Leo Dennis</a></span>
                              <span><i class="fa fa-date"></i> June 10, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 48 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a href="single-post.html" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-video">
                              <div class="embed-responsive embed-responsive-16by9">
                                   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Pgmx7z49OEk" allowfullscreen></iframe>
                              </div>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">Nam interdum maximus dolor faucibus</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> May 30, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 63 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a href="single-post.html" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="single-post.html">
                                   <img src="images/blog-image3.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">The ingredients that make a great burger</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="images/author-image2.jpg" class="img-responsive img-circle"> Leo Dennis</a></span>
                              <span><i class="fa fa-date"></i> April 18, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 124 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a href="single-post.html" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="single-post.html">
                                   <img src="images/blog-image4.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">Vestibulum vel mauris nec ex tempus</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> March 12, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 256 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a href="single-post.html" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>
               </div>
               {% endblock inner_content %}
          </div>
     </div>
</section>

<!-- Footer Section -->

<footer>
     <div class="container">
          <div class="row">

               <div class="col-md-5 col-md-offset-1 col-sm-6">
                    <h3>Neuron Studio</h3>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                    <div class="footer-copyright">
                         <p>Copyright &copy; 2017 Your Company - Design: Tooplate</p>
                    </div>
               </div>

               <div class="col-md-4 col-md-offset-1 col-sm-6">
                    <h3>Talk to us</h3>
                    <p><i class="fa fa-globe"></i> 512 Delicious Street, San Francisco, CA 10880</p>
                    <p><i class="fa fa-phone"></i> 010-020-0990</p>
                    <p><i class="fa fa-save"></i> info@company.com</p>
               </div>

               <div class="clearfix col-md-12 col-sm-12">
                    <hr>
               </div>

               <div class="col-md-12 col-sm-12">
                    <ul class="social-icon">
                         <li><a href="#" class="fa fa-facebook"></a></li>
                         <li><a href="#" class="fa fa-twitter"></a></li>
                         <li><a href="#" class="fa fa-google-plus"></a></li>
                         <li><a href="#" class="fa fa-dribbble"></a></li>
                         <li><a href="#" class="fa fa-linkedin"></a></li>
                    </ul>
               </div>
               
          </div>
     </div>
</footer>

<!-- Back top -->
<a href="#back-top" class="go-top"><i class="fa fa-angle-up"></i></a>

<!-- SCRIPTS -->

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/particles.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
<script src="{% static "js/jquery.parallax.js" %}"></script>
<script src="{% static "js/smoothscroll.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>

</body>
</html>

switch/switchblog/templates/create-post.html
{% extends 'base.html' %}
{% block title %} Create Blog Post {% endblock title %}

{% block inner_content %}
    <form class="west" method="post" action="{% url 'blog:create-post' %}" enctype="multipart/form-data"> 
        {% csrf_token %}
        {{ article_form.as_p }}
        <input type="file" name="post_image" placeholder="select_image"/>
        <input type="submit" value="Submit Article" class="btn btn-success" name="submit"/>
        
    </form>
{% endblock inner_content %}

switch/switchblog/templates/index.html
{% extends 'base.html' %}
{% block title %} This is a blog index page {% endblock title %}

{% block inner_content %}
    <div>
        <a href="{% url 'blog:create-post' %}" class="btn btn-primary">Create New Post</a>
        <h5>This is the inner content of the blog index page </h5>
    </div>
{% endblock inner_content %}